# Generated by Django 5.1.1 on 2024-11-07 20:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = []
