# Generated by Django 5.1.1 on 2024-11-07 20:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0002_auto_20241107_2007"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="car",
            name="image",
        ),
        migrations.AddField(
            model_name="car",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="depreciation_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Afschrijvingsbijdrage per boeking",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="fuel_cost_per_km",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Brandstofkosten per kilometer",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="hourly_rate",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="insurance_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Verzekeringsbijdrage per boeking",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="maintenance_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Onderhoudsbijdrage per boeking",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="brand",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="car",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="license_plate",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="car",
            name="model",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="car",
            name="year",
            field=models.IntegerField(),
        ),
    ]
