# Generated by Django 5.1.1 on 2024-11-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="expected_kilometers",
            field=models.DecimalField(
                decimal_places=1,
                default=50.0,
                help_text="Verwacht aantal kilometers",
                max_digits=6,
            ),
        ),
    ]
